### ISSUE TITLE
Error in spelling of Computer in the README.md file

### ISSUE THREAD

**Issue by Sankalpa-Sarkar** [Vivek-Raman/CS-Through-The-Ages#1]
Computer is typed as Coputer in the README.md file of the project. 

![WhatsApp Image 2020-08-12 at 19 57 30](https://user-images.githubusercontent.com/47474648/90027947-b837d400-dcd6-11ea-892b-b27c4b10ae44.jpeg)

**Comment by Vivek-Raman** [comment]
Thanks mate!
